version: "3.9"

services:
#
#  automation:
#    build: automation
#    volumes:
#      - ./allure-results:/tmp/automation/build/allure-results


  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    shm_size: 2gb
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    ports:
      - '7900-7900'

  firefox:
    image: selenium/node-firefox-debug:latest
    container_name: firefox
    shm_size: 2gb
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    depends_on:
      - selenium-hub
    ports:
      - '7901-7901'